###
GET http://localhost:4000/

###
POST http://localhost:4000/username
content-type: application/json

{
	"username": "Harry"
}

###
POST http://localhost:4000/formdata
content-type: application/x-www-form-urlencoded 

username=Harry&age=13