###
GET http://localhost:4000/

###
GET http://localhost:4000/post

###
GET http://localhost:4000/user/1/harry

###
POST http://localhost:4000/user/json
content-type: application/json

{
	"user": "Harry",
	"id": 1
}

###
POST http://localhost:4000/user/form
content-type: application/x-www-form-urlencoded 

user=Harry&id=13

###
GET http://localhost:4000/item/query?tier=1&name=Daedric_Sword

###
POST http://localhost:4000/item/json
content-type: application/json

{
	"tier": 1,
	"name": "Daedric greatsword"
}

###
GET http://localhost:4000/states/name

###
GET http://localhost:4000/req/add

###
GET http://localhost:4000/error/more/3

###
POST http://localhost:4000/either/lang
Content-Type: text/plain

Hooh
